### PR TITLE
fixing the sorted Swedish contact data

### PR DESCRIPTION
**Pull request by mattiasaxell**
Noticed I had configured some columns incorrectly. Now updated with added customised columns for Sweden and data sorted correctly.

### CODE REVIEW

**Comment by todrobbins** [comment]
@mattiasaxell it looks like you're missing `id` values, which are the URL slugs.

**Comment by mattiasaxell** [comment]
@todrobbins you're totally right! I'm aware of that issue, I need help to automatically combine "{jurisdiction-code}/{unique-id-for-body-within-jurisdiction}". Perhaps with an LibreOffice-formula?

**Comment by todrobbins** [comment]
Let me see if I can help. I'd really recommend we resolve that before merging. 🛠

**Comment by mattiasaxell** [comment]
Would be great! I couldn't find any guide to formatting accordingly to used standard, if you could document how you (or I could) do it I would love to learn! My main purpose for doing this is to gather them nicely for launch of Alavateli FOI platform.

**Comment by rgrp** [comment]
@todrobbins great assistance!

@mattiasaxell great contribution and thank-you for submitting this. I should say that is is ok to have numeric identifiers - though could you explain where the identifiers got generated from?

@todrobbins & @mattiasaxell assuming the numeric ids are good vs something more "slug" like all you would need to do is prefix with swedish 2 digit iso code which is "se" e.g. `se/{numeric-id}`

I am also cc'ing @augusto-herrmann as he has become informal editor for this dataset!

**Comment by mattiasaxell** [comment]
@rgrp you're very welcome. Needed to get contact details for Alaveteli/FROIDE FOI platform anyway. :)
I mistook the id column as a way to add Swedish organisational number. I changed that in second pull request and created org_id column. There's no source for id so I guess slug should replace it what you currently see in id.

@rgrp I'd be grateful if @todrobbins helps out with creating these slugs, I have no idea how to.

I should also mention that these details are from fall 2015. I have had to e-mail authorities or download authorities by category in bulk to put together to one CSV (until they start pushing to GitHub themselves :smile:).

**Comment by rgrp** [comment]
@mattiasaxell amazing work.

@todrobbins @augusto-herrmann can you guys take a look here and get this merged in :-)

/cc @danfowler

**Comment by todrobbins** [comment]
I'm still working on the slugs, but we could merge now and add that later. Thoughts?

**Comment by mattiasaxell** [comment]
@todrobbins I'm realizing now that I can add embassies, which is a bit difficult, but then make another PR with that fix. Would it be better for your work on slugs? I assume it could make easier to maintain it later.

**Comment by todrobbins** [comment]
@mattiasaxell I'm going to merge this pull request and let you carry on with adding the embassies while I also work on the slugs. Thanks!

**Comment by augusto-herrmann** [comment]
Ok, I've added issue #71 to keep track of what still needs to be done.
Thanks for the the contribution, @mattiasaxell !

**Pull request merged**
