### PR TITLE
Added italian data from official sources and script to update the data

### PR DESCRIPTION
**Pull request by traversaro**
All the issues mentioned in the discussion in https://github.com/okfn/publicbodies/issues/16 still apply (licence, public bodies to consider).
I have eliminated only the schools, but the categories to eliminate can be selected in the import script. Allso eliminating the schools there are still ~11000 public bodies (of which ~8000 are municipalities).

### CODE REVIEW

**Comment by rgrp** [comment]
@augusto-herrmann could you do a review and merge if appropriate ...

**Comment by todrobbins** [comment]
@traversaro @rufuspollock I'll review this tomorrow. 👍🏻

**Comment by traversaro** [comment]
Warning: the last time I run that script was probably 3.5 years ago, so I don't know if it is still working.

**Comment by todrobbins** [comment]
@traversaro right! Did you want to update the pull request before I review?

**Comment by traversaro** [comment]
The source file seems to be still there and use the same format, so feel free to review it, for a few days I will not be able to run the script to update the data.

**Pull request merged**
