### PR TITLE
Fix the source URL for Italian data

### PR DESCRIPTION
**Pull request by traversaro**
Old:  http://www.indicepa.gov.it/ricerca/dettaglioamministrazione.php?cod_amm=c_l745 
New; http://www.indicepa.gov.it/ricerca/n-dettaglioamministrazione.php?cod_amm=c_l745

### CODE REVIEW

**Comment by todrobbins** [comment]
Thank you @traversaro!

**Comment by todrobbins** [comment]
PS @traversaro: does the dataset `data/it.csv` need to be updated with this new script?

**Comment by traversaro** [comment]
Yes. What is the policy? Run the script and add the updated dataset in the PR?

**Comment by todrobbins** [comment]
We haven't set up any jobs to run scripts routinely. Could you update the dataset and submit a pull request? 👍🏻

**Pull request merged**
